// Turn the site's spring specs into CSS `linear()` easings, so hover and state
// transitions keep Framer's spring feel without a JS animation library.
//
//   npm run springs   ->  writes src/styles/springs.css
//
// Duration-based springs ({ bounce, duration }) are converted to stiffness/damping
// the way Motion does it (findSpring: Newton's method on the settling envelope),
// then every spring is integrated from 0 to rest and sampled evenly.
import fs from 'node:fs'

/** The whole vocabulary. Names describe the feel; comments say who uses it. */
const SPRINGS = {
  // Framer's default: FAQ items, testimonial thumbnails, mobile menu
  default: { bounce: 0.2, duration: 0.4 },
  // mobile header open/close
  flat: { bounce: 0, duration: 0.4 },
  // nav tabs, book-a-call card, project cards, service cards, footer links, testimonial card
  soft: { stiffness: 200, damping: 30, mass: 1 },
  // primary button, client logos
  firm: { stiffness: 400, damping: 40, mass: 1 },
  // the social links' rolling label
  roll: { stiffness: 150, damping: 30, mass: 1 },
  // hero and header entrance
  appear: { stiffness: 320, damping: 60, mass: 1 },
  // project hero: the side visuals settling into place
  stage: { bounce: 0, duration: 1.4 },
  // project hero: the columns that wipe off the project screen
  wipe: { bounce: 0, duration: 1.2 },
  // project hero: each letter of the tagline, and the big word
  letter: { bounce: 0, duration: 0.85 },
  word: { bounce: 0, duration: 1.1 },
}

const SAFE_MIN = 0.001

function findSpring({ bounce, duration, mass = 1 }) {
  const zeta = Math.min(1, Math.max(0.05, 1 - bounce))
  const T = Math.min(10, Math.max(0.01, duration))
  let envelope, derivative
  if (zeta < 1) {
    const angular = (w) => w * Math.sqrt(1 - zeta * zeta)
    envelope = (w) => SAFE_MIN - ((w * zeta) / angular(w)) * Math.exp(-w * zeta * T)
    derivative = (w) => {
      const delta = w * zeta * T
      const e = zeta * zeta * w * w * T
      const g = w * w * Math.sqrt(1 - zeta * zeta)
      const factor = -envelope(w) + SAFE_MIN > 0 ? -1 : 1
      return (factor * (0 - e) * Math.exp(-delta)) / g
    }
  } else {
    envelope = (w) => -SAFE_MIN + Math.exp(-w * T) * (w * T + 1)
    derivative = (w) => Math.exp(-w * T) * (T * T * -w)
  }
  let w = 5 / T
  for (let i = 0; i < 12; i++) w -= envelope(w) / derivative(w)
  const stiffness = w * w * mass
  return { stiffness, damping: zeta * 2 * Math.sqrt(mass * stiffness), mass }
}

/** Integrate x'' = (-k(x-1) - c x') / m from rest at 0 until it settles at 1. */
function simulate({ stiffness: k, damping: c, mass: m }) {
  const dt = 1 / 2000
  const accel = (x, v) => (-k * (x - 1) - c * v) / m
  let x = 0
  let v = 0
  let t = 0
  const samples = [[0, 0]]
  while (t < 5) {
    // RK4
    const k1x = v, k1v = accel(x, v)
    const k2x = v + (dt / 2) * k1v, k2v = accel(x + (dt / 2) * k1x, v + (dt / 2) * k1v)
    const k3x = v + (dt / 2) * k2v, k3v = accel(x + (dt / 2) * k2x, v + (dt / 2) * k2v)
    const k4x = v + dt * k3v, k4v = accel(x + dt * k3x, v + dt * k3v)
    x += (dt / 6) * (k1x + 2 * k2x + 2 * k3x + k4x)
    v += (dt / 6) * (k1v + 2 * k2v + 2 * k3v + k4v)
    t += dt
    samples.push([t, x])
    if (Math.abs(1 - x) < 0.001 && Math.abs(v) < 0.01) break
  }
  return { duration: t, samples }
}

function toLinear({ duration, samples }, points = 48) {
  const out = []
  for (let i = 0; i <= points; i++) {
    const t = (i / points) * duration
    const j = Math.min(samples.length - 1, Math.round(t * 2000))
    out.push(i === points ? 1 : +samples[j][1].toFixed(4))
  }
  return `linear(${out.join(', ')})`
}

let css = '/* Generated by scripts/gen-springs.mjs; edit the spring table there, not this file. */\n:root {\n'
for (const [name, spec] of Object.entries(SPRINGS)) {
  const physical = 'stiffness' in spec ? spec : findSpring(spec)
  const sim = simulate(physical)
  const label = 'stiffness' in spec ? `stiffness ${spec.stiffness}, damping ${spec.damping}` : `bounce ${spec.bounce}, duration ${spec.duration}s`
  css += `  /* ${label} -> k ${physical.stiffness.toFixed(1)}, c ${physical.damping.toFixed(1)} */\n`
  css += `  --spring-${name}: ${toLinear(sim)};\n`
  css += `  --spring-${name}-duration: ${Math.round(sim.duration * 1000)}ms;\n`
}
css += '}\n'
fs.writeFileSync('src/styles/springs.css', css)
console.log(css)
